<template>
  <div>
    <h4>
      Show Random number generated by a function in composables:{{
        randomNumber
      }}
    </h4>
    <hr class="m-5">
    <h4>
      Use Composiables inappropriately (without useState when return value can
      change): {{ RandomNumNoUseState }}
    </h4>
    <hr class="m-5">
    <h4>No need for useState if value does not change: {{ valueNoChange }}</h4>
  </div>
</template>

<script setup>
const randomNumber = giveRandomNum()
const RandomNumNoUseState = giveRandomNumNoUseState()
const valueNoChange = staticValue()
</script>

<style lang="scss" scoped></style>
